name = "Nuclear Repulsor Shields"
uid = "44844B72-6054-3656-0210-D5FA6066FB5E"
version = 21
copyright = "2016-2021 Uveso"
description = "(For all gameversions) Experimental shields with nuclear repulsor technology, so nuke missiles can't penetrate them."
author = "Uveso"
url = "https://forum.faforever.com/topic/357"
icon = "/mods/NuclearRepulsorShields/NukRepShield.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
